POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Sydney OPera House",
  "author": "Fabius Maximus",
  "url": "https://opera.dev",
  "likes": 109,
  "userId": "675e8b15efd95f0041dd5fb7"
}